[package]
name = "svc"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "svc"
path = "src/main.rs"

[dependencies]
svc-core.workspace = true
svc-repo = { path = "../svc-repo" }
clap.workspace = true
serde.workspace = true
serde_json = "1"
tokio.workspace = true
agent-client-protocol.workspace = true
